/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

int main(void)
{
	ai_handle my_model = AI_HANDLE_NULL;
    
    ai_network_create(&my_model, AI_NETWORK_DATA_CONFIG);

    ai_network_init(my_model, AI_NETWORK_DATA_CONFIG);
    /* Loop forever */
	for(;;);
}
