/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdio.h>
#include <stdint.h>

// Core ST EdgeAI 4.0 runtime API
#include "stai.h" 
#include "network.h"
#include "network_data.h"

int main(void) {
    stai_return_code status;
    
    // 1. Allocate space for the model runtime context structure using the local definition
    static uint8_t network_ctx_buffer[AI_NETWORK_CTX_SIZE_BYTES];
    stai_network* network = (stai_network*)network_ctx_buffer;

    // 2. Point to your 159 KB weights array located in network_data.c
    stai_ptr weights_buffer = (stai_ptr)g_network_weights_array;

    // 3. Initialize the network object container (Passing only the single context pointer argument)
    status = stai_network_init(network);
    if (status != STAI_SUCCESS) {
        // Initialization failed
        while(1);
    }

    // 4. Bind your 159 KB of weights to the initialized network context
    status = stai_network_set_weights(network, &weights_buffer, 1);
    if (status != STAI_SUCCESS) {
        // Weights binding failed
        while(1);
    }

    // 5. Setup your runtime RAM activation buffers (17,920 Bytes required)
    static uint8_t activation_buffer[17920] __attribute__((aligned(8)));
    stai_ptr act_ptr = (stai_ptr)activation_buffer;
    
    status = stai_network_set_activations(network, &act_ptr, 1);
    if (status != STAI_SUCCESS) {
        while(1);
    }

    while (1) {
        // Your main inference and pipeline code can now run here safely
    }
}
