/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE for Visual Studio Code Extension
 * @brief          : Main program body with RF validation logic
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2025 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */
#include <stdio.h>
#include <stdint.h>

// Core ST EdgeAI 4.0 runtime API
#include "stai.h" 
#include "network.h"
#include "network_data.h"

// Include your custom validation data header
#include "data.h"

/* * NOTE: Ensure that data.h declares your array. 
 * If it is defined as: static const int8_t rf_validation_signal[] = {...}; 
 * then it is already visible here.
 */


// External declaration of your UART handle (CubeMX usually defines this in main.c or usart.c)
extern UART_HandleTypeDef huart3; 

/**
 * @brief Redirects printf standard output to the UART peripheral.
 * This function overrides the weak symbol used by the C standard library.
 */
int _write(int file, char *ptr, int len) {
    // Transmit the string over UART3 (the default Virtual COM port for the NUCLEO-H753ZI)
    // We use a generous timeout value (HAL_MAX_DELAY) to ensure messages aren't cut off
    HAL_StatusTypeDef status = HAL_UART_Transmit(&huart3, (uint8_t*)ptr, len, HAL_MAX_DELAY);
    
    // Return the number of characters written if successful, or -1 on error
    return (status == HAL_OK) ? len : -1;
}

int main(void) {
    stai_return_code status;
    
    // 1. Allocate space for the model runtime context structure using the exact macro from network.h
    static uint8_t network_ctx_buffer[STAI_NETWORK_CONTEXT_SIZE];
    stai_network* network = (stai_network*)network_ctx_buffer;

    // 2. Point to your weights array located in network_data.c
    stai_ptr weights_buffer = (stai_ptr)g_network_weights_array;

    // 3. Initialize the network object container
    status = stai_network_init(network);
    if (status != STAI_SUCCESS) {
        // Initialization failed
        while(1);
    }

    // 4. Bind your model weights to the initialized network context
    status = stai_network_set_weights(network, &weights_buffer, STAI_NETWORK_WEIGHTS_NUM);
    if (status != STAI_SUCCESS) {
        // Weights binding failed
        while(1);
    }

    // 5. Setup your runtime RAM activation buffers using the exact size macro
    static uint8_t activation_buffer[STAI_NETWORK_ACTIVATIONS_SIZE_BYTES] __attribute__((aligned(STAI_NETWORK_CONTEXT_ALIGNMENT)));
    stai_ptr act_ptr = (stai_ptr)activation_buffer;

    status = stai_network_set_activations(network, &act_ptr, STAI_NETWORK_ACTIVATIONS_NUM);
    if (status != STAI_SUCCESS) {
        // Activation buffer binding failed
        while(1);
    }

    // 6. Allocate Input and Output buffers matching network specifications
    static uint8_t input_buffer[STAI_NETWORK_INPUT_1_SIZE_BYTES] __attribute__((aligned(STAI_NETWORK_INPUT_1_ALIGNMENT)));
    static uint8_t output_buffer[STAI_NETWORK_OUTPUT_1_SIZE_BYTES] __attribute__((aligned(STAI_NETWORK_OUTPUT_1_ALIGNMENT)));

    // 7. Load your validation data from data.h into the runtime input buffer
    // Adjust casting if your network expects a different datatype configuration (e.g., float)
    for (uint32_t i = 0; i < STAI_NETWORK_INPUT_1_SIZE_BYTES; i++) {
        // Safeguard to ensure we don't read past the bounds of your input array
        if (i < sizeof(rf_validation_signal)) {
            input_buffer[i] = (uint8_t)rf_validation_signal[i];
        } else {
            input_buffer[i] = 0; // Pad with zeros if your dataset array is smaller than network input size
        }
    }

    // Define tensor buffers pointing to our runtime arrays
    stai_tensor_buffer input_tensor = { .ptr = (stai_ptr)input_buffer };
    stai_tensor_buffer output_tensor = { .ptr = (stai_ptr)output_buffer };

    // 8. Execute model inference on the STM32H753ZI core
    status = stai_network_run(network, &input_tensor, STAI_NETWORK_INPUTS_NUM, 
                              &output_tensor, STAI_NETWORK_OUTPUTS_NUM);
    
    if (status != STAI_SUCCESS) {
        // Inference execution failed
        while(1);
    }

    // 9. Process the classification probabilities from the output buffer
    // Most RF classifiers output an array of floats representing Softmax confidences
    float* probabilities = (float*)output_buffer;
    uint32_t num_classes = STAI_NETWORK_OUTPUT_1_SIZE_BYTES / sizeof(float);
    
    uint32_t highest_prob_class = 0;
    float max_prob = -1.0f;

    for (uint32_t c = 0; c < num_classes; c++) {
        if (probabilities[c] > max_prob) {
            max_prob = probabilities[c];
            highest_prob_class = c;
        }
    }

    // If you have implemented a custom _write() function to override printf to UART:
    printf("Predicted Modulation Class: %lu with confidence %.2f%%\r\n", highest_prob_class, max_prob * 100.0f);

    while(1) {
        // Execution finished successfully. Hang or toggle a LED to visually indicate completion.
    }
}
