#include <stdio.h>
#include <stdint.h>
#include <string.h>

// 1. Core STM32 Architecture & HAL Configuration
// Replace with "stm32f4xx_hal.h", "stm32l4xx_hal.h", etc., depending on your target MCU
#include "stm32h7xx_hal.h" 

// 2. ST EdgeAI 4.0 Runtime & Network Headers
#include "stai.h"
#include "network.h"       // Auto-generated by ST EdgeAI tools (contains weights arrays, size macros, etc.)
#include "network_data.h"  // Contains the actual g_network_weights_array declaration

// 3. Peripheral Handlers (Usually managed via CubeMX / main.h)
extern UART_HandleTypeDef huart3; 

// 4. Static Input/Output Model Tensors (Using Correct ST EdgeAI 4.0 Macro Conventions)
static uint8_t input_buffer[STAI_NETWORK_IN_1_SIZE_BYTES] __attribute__((aligned(STAI_NETWORK_IN_1_ALIGNMENT)));
static uint8_t output_buffer[STAI_NETWORK_OUT_1_SIZE_BYTES] __attribute__((aligned(STAI_NETWORK_OUT_1_ALIGNMENT)));

// 5. System Clock Configuration Protocol Prototype
void SystemClock_Config(void);
static void MX_USART3_UART_Init(void);

int main(void)
{
    // Initialize Hardware Abstraction Layer & Core Peripherals
    HAL_Init();
    SystemClock_Config();
    MX_USART3_UART_Init();

    printf("--- Starting ST EdgeAI Inference --- \r\n");

    stai_return_code status;

    // 6. Allocate Context Buffer & Create Network Instance Handler
    static uint8_t network_ctx_buffer[STAI_NETWORK_CONTEXT_SIZE];
    stai_network* network = (stai_network*)network_ctx_buffer;

    // Initialize Network Instance
    status = stai_network_init(network);
    if (status != STAI_SUCCESS) {
        printf("CRITICAL ERROR: Failed to initialize EdgeAI Network. Code: %d\r\n", status);
        while(1);
    }

    // 7. Bind Trained Model Weights
    // g_network_weights_array is defined inside your generated network_data.c / network_data.h
    stai_ptr weights_buffer = (stai_ptr)g_network_weights_array; 
    status = stai_network_set_weights(network, &weights_buffer, STAI_NETWORK_WEIGHTS_NUM);
    if (status != STAI_SUCCESS) {
        printf("CRITICAL ERROR: Failed to bind weights. Code: %d\r\n", status);
        while(1);
    }

    // 8. Bind Runtime Activation Memory (Scratchpad RAM)
    static uint8_t activation_buffer[STAI_NETWORK_ACTIVATIONS_SIZE_BYTES] __attribute__((aligned(STAI_NETWORK_CONTEXT_ALIGNMENT)));
    stai_ptr act_ptr = (stai_ptr)activation_buffer;

    status = stai_network_set_activations(network, &act_ptr, STAI_NETWORK_ACTIVATIONS_NUM);
    if (status != STAI_SUCCESS) {
        printf("CRITICAL ERROR: Failed to bind activation buffer. Code: %d\r\n", status);
        while(1);
    }

    // 9. Configure Data I/O Descriptors (STAI Buffers)
    stai_buffer input_tensor  = { .ptr = (stai_ptr)input_buffer };
    stai_buffer output_tensor = { .ptr = (stai_ptr)output_buffer };

    // --- Demo Application Processing Loop ---
    while (1)
    {
        // [Optional]: Populate your input_buffer here with sensors/mock data
        // e.g., memcpy(input_buffer, external_sensor_payload, STAI_NETWORK_IN_1_SIZE_BYTES);

        printf("Running Model Inference...\r\n");

        // 10. Execute Model Inference
        status = stai_network_run(network, 
                                  STAI_MODE_SYNC, 
                                  &input_tensor, 
                                  STAI_NETWORK_IN_NUM, 
                                  &output_tensor, 
                                  STAI_NETWORK_OUT_NUM);

        if (status == STAI_SUCCESS) {
            printf("Inference Completed Successfully!\r\n");
            // [Optional]: Parse output_buffer payload results here
        } else {
            printf("Inference Execution Failed! Code: %d\r\n", status);
        }

        HAL_Delay(1000); // Wait 1 second between inferences
    }
}

/**
  * @brief USART3 Initialization Function (Example wrapper; modify to match your pinouts)
  */
static void MX_USART3_UART_Init(void)
{
    // If peripheral init is handled inside your main.h / stm32h7xx_hal_msp.c, 
    // you can safely leave this or rely on CubeMX's auto-generated initialization logic.
}

/**
  * @brief System Clock Configuration
  */
void SystemClock_Config(void)
{
    // Auto-generated by CubeMX based on your specific development board
}

/**
  * @brief Redirects printf to UART over ST-Link Virtual COM Port
  */
int _write(int file, char *ptr, int len)
{
    HAL_UART_Transmit(&huart3, (uint8_t*)ptr, len, HAL_MAX_DELAY);
    return len;
}
